### ISSUE TITLE
Code and dataset availability

### ISSUE THREAD

**Issue by hanjq17** [mkofinas/aether#1]
Hi authors,

Thanks for the nice work! Just kindly asking when the code and dataset with split to reproduce your result will be available?

Best,
Jiaqi

**Comment by mkofinas** [comment]
Hi Jiaqi,

Thank you for your interest in our work! :slightly_smiling_face: I am currently in the process of cleaning up the code. I plan to release the code and the datasets in the next 2-3 weeks.

Best,
Miltos

**Comment by mkofinas** [comment]
Dear Jiaqi,

The code cleanup took longer than expected, but I have now released the source code and the datasets. I am closing this issue, but feel free to create a new one if you have more questions.

Best,
Miltos
